### ISSUE TITLE
More Consistent Scrolling in Control Palette

### ISSUE THREAD

**Issue by Kensai2000** [writemonkey/wm3#53] opened 2016-06-21 20:15 UTC
When scrolling up and down the control palette with the arrow keys, once you've moved the cursor far enough down the list to scroll it at all, if you reverse and arrow up, the selection, while being the correct one, will reposition to the top of the palette, and then when you arrow down again, it jumps back down. Its not selecting incorrectly, but the activity is visually disorienting.

**Comment by writemonkey** [comment] 2016-06-22 06:32
Hi, this is a duplicate of no #14 and will be fixed!

**Comment by Kensai2000** [comment] 2016-06-22 16:09
Dangit! Sorry about that.

**Closed** 2016-06-22 16:19 UTC
