### ISSUE TITLE
Word with single tick flagged as spelling error.

### ISSUE THREAD

**Issue by jmcd040** [writemonkey/wm3#297] opened 2019-05-18 18:52 UTC
'Part' is flagged as a spelling error. So is 'Part as in 'Part 1'

**Comment by Gerard-RvE** [comment] 2019-07-19 09:14
Isn't this a duplicate of #267?

**Comment by jmcd040** [comment] 2019-07-19 13:50
Yep, you're right. I forgot about reporting it 4 months ago. I use WM frequently and still seeing all these kinds of items flagged as spelling errors is distracting.

**Closed** 2019-07-19 13:50 UTC

**Comment by Gerard-RvE** [comment] 2019-07-22 08:35
Agreed that it's very distracting. I use it for writing academic articles, and in my references titles are in quotation marks. Spell checker is absolutely worthless there. Therefor remembered this was already reported.
